var items =
  {
  "login": "JSharpie",
  "id": 14966326,
  "avatar_url": "https://avatars.githubusercontent.com/u/14966326?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/JSharpie",
  "html_url": "https://github.com/JSharpie",
  "followers_url": "https://api.github.com/users/JSharpie/followers",
  "following_url": "https://api.github.com/users/JSharpie/following{/other_user}",
  "gists_url": "https://api.github.com/users/JSharpie/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/JSharpie/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/JSharpie/subscriptions",
  "organizations_url": "https://api.github.com/users/JSharpie/orgs",
  "repos_url": "https://api.github.com/users/JSharpie/repos",
  "events_url": "https://api.github.com/users/JSharpie/events{/privacy}",
  "received_events_url": "https://api.github.com/users/JSharpie/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Jacob Sharp",
  "company": null,
  "blog": null,
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "public_repos": 8,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2015-10-04T17:29:38Z",
  "updated_at": "2015-10-08T05:49:56Z"
};
